import PDFDocument from 'pdfkit';
import type { Response } from 'express';

export function streamPdf(res: Response, filename: string, build: (doc: PDFKit.PDFDocument) => void) {
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  const doc = new PDFDocument({ margin: 50 });
  doc.pipe(res);
  build(doc);
  doc.end();
}

export function writeScorecardPdf(
  doc: PDFKit.PDFDocument,
  data: {
    title: string;
    sport: string;
    homeTeam: string;
    awayTeam: string;
    homeScore: number;
    awayScore: number;
    homeWickets?: number;
    awayWickets?: number;
    winner?: string;
    details?: string[];
  }
) {
  doc.fontSize(22).text('SportSync Scorecard', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(14).fillColor('#666').text(data.title, { align: 'center' });
  doc.fillColor('#000');
  doc.moveDown(1.5);

  doc.fontSize(16).text(`${data.homeTeam}  vs  ${data.awayTeam}`, { align: 'center' });
  doc.moveDown(0.5);

  const homeDisplay =
    data.sport === 'indoor-cricket'
      ? `${data.homeScore}/${data.homeWickets ?? 0}`
      : String(data.homeScore);
  const awayDisplay =
    data.sport === 'indoor-cricket'
      ? `${data.awayScore}/${data.awayWickets ?? 0}`
      : String(data.awayScore);

  doc.fontSize(28).text(`${homeDisplay}  –  ${awayDisplay}`, { align: 'center' });
  doc.moveDown(1);

  if (data.winner) {
    doc.fontSize(14).text(`Winner: ${data.winner}`, { align: 'center' });
    doc.moveDown(1);
  }

  if (data.details?.length) {
    doc.fontSize(12).text('Match Details', { underline: true });
    doc.moveDown(0.5);
    for (const line of data.details) {
      doc.text(line);
    }
  }

  doc.moveDown(2);
  doc.fontSize(9).fillColor('#999').text(`Generated by SportSync · ${new Date().toLocaleString()}`, {
    align: 'center',
  });
}

export function writeLadderPdf(
  doc: PDFKit.PDFDocument,
  data: {
    competitionName: string;
    rows: { position: number; team: string; played: number; won: number; lost: number; points: number }[];
  }
) {
  doc.fontSize(22).text('Competition Ladder', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(14).fillColor('#666').text(data.competitionName, { align: 'center' });
  doc.fillColor('#000');
  doc.moveDown(1.5);

  const startY = doc.y;
  const colX = [50, 90, 280, 340, 380, 420, 470];
  const headers = ['#', 'Team', 'P', 'W', 'L', 'Pts'];

  doc.fontSize(11).font('Helvetica-Bold');
  headers.forEach((h, i) => doc.text(h, colX[i], startY, { width: i === 1 ? 180 : 40 }));
  doc.moveDown(0.5);
  doc.font('Helvetica');

  for (const row of data.rows) {
    const y = doc.y;
    doc.text(String(row.position), colX[0], y);
    doc.text(row.team, colX[1], y, { width: 180 });
    doc.text(String(row.played), colX[2], y);
    doc.text(String(row.won), colX[3], y);
    doc.text(String(row.lost), colX[4], y);
    doc.text(String(row.points), colX[5], y);
    doc.moveDown(0.4);
  }
}
